modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20World%20Border"
logoFile="icon.png"

[[mods]]
modId="worldborder"
version="5.0"
displayName="World Border"
displayURL="https://serilum.com/mod/world-border"
authors="Serilum"
description='''Allows the creation of a configurable world border for each dimension, limiting the world size.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.worldborder]]
    modId="collective"
    mandatory=true
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.worldborder]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"
